import { Router } from "express";
import fs from "node:fs";
import path from "node:path";
import mongoose from "mongoose";
import { requireAuth } from "../middleware/requireAuth.js";
import { DEPARTMENTS } from "../../data_gen/referenceData.js";

export const metaRouter = Router();
metaRouter.use(requireAuth);

metaRouter.get("/", async (req, res) => {
  const db = mongoose.connection.db;
  const competencies = await db.collection("competencies").find({}).toArray();
  res.json({ departments: DEPARTMENTS, competencies });
});

// Curated demo entry points — generated by data_gen/generate.js at dataset
// build time (see scripts/generateData.js), never hardcoded here. Cached in
// module scope after first read; a `npm run generate-data` re-run means a
// server restart is needed to pick up the new file, same as ground_truth.json.
let showcaseCache = null;
metaRouter.get("/showcase", (req, res) => {
  if (!showcaseCache) {
    const showcasePath = path.resolve("data_gen", "showcase.json");
    if (!fs.existsSync(showcasePath)) {
      return res.json({ showcases: [], note: "No showcase.json — run npm run generate-data to produce one." });
    }
    showcaseCache = JSON.parse(fs.readFileSync(showcasePath, "utf8"));
  }
  res.json({ showcases: showcaseCache });
});
